rate-limiter:
  status:
    second: -1
    minute: 2
    hour: -1
    day: -1
  news:
    second: 2
    minute: -1
    hour: -1
    day: 20
  marketing:
    second: -1
    minute: -1
    hour: 3
    day: -1